### ISSUE TITLE
Bug: search results table is formatted strangely on macOS Safari 16.0, chrome 106

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari.github.io#370] opened 2022-10-21 13:54 UTC
The search results are presented oddly with the text crushed on the side and the name of the page in a wide column.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/197204461-9bc6b5cd-4850-40d0-9520-0f538718f1c8.png">

**Comment by melissawm** [comment] 2022-10-28 22:56
Hi @psobolewskiPhD - this is a duplicate of #357 and should be fixed by #367, so I'm closing this issue in favor of that one. Please reopen if necessary. Thanks!

**Closed as completed by melissawm** 2022-10-28 22:56 UTC
