### ISSUE TITLE
[dev] website issue: Search bar obscured by top nav bar 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari.github.io#378] opened 2023-01-10 09:18 UTC
On the `latest` version of napari.org—use the version switcher—the search bar is obscured by the top navigation bar:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/76622105/211510533-2283d0e1-ea76-49cb-9f6f-57bd1fdcc0f0.png">
Switching back to `stable` resolves the issue.

macOS 13.1
Safari 16.2
Chrome 108.0.5359.124

**Comment by jni** [comment] 2023-01-10 12:03
Duplicate of napari/napari-sphinx-theme#128. It should be resolved there, so I'll close this.

**Closed as completed by jni** 2023-01-10 12:03 UTC

**Comment by psobolewskiPhD** [comment] 2023-01-10 13:21
Oh, sorry! I never know the right place for these things related to the website.
docs
sphinx
this repo
blerg!

**Comment by jni** [comment] 2023-01-10 22:15
Haha it's true! Definitely all too complicated. Guh.

**Comment by psobolewskiPhD** [comment] 2023-01-11 07:42
I guess I should drill into my head that content issues are napari/docs
and formatting napari-sphinx?
And never use this one? 🤣
